production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || ENV['MONGOLAB_URI'] %>
development:
  clients:
    default:
      uri: mongodb://localhost:27017/takuhai_tracker
test:
  clients:
    default:
      uri: mongodb://localhost:27017/takuhai_tracker
